# Wi-Fi connection settings
WIFI_SSID = "your_wifi_ssid_here"
WIFI_PASSWORD = "your_wifi_password_here"

# SwitchBot BLE API
SWITCHBOT_SERVICE_UUID = "SWITCHBOT_SERVICE_UUID"
SWITCHBOT_CHARACTERISTIC_UUID = "SWITCHBOT_CHARACTERISTIC_UUID"

# SwitchBot Web API
SWITCHBOT_BASE_URL = "SWITCHBOT_BASE_URL"
SWITCHBOT_API_TOKEN = "YOUR_SWITCHBOT_API_TOKEN"
SWITCHBOT_API_CLIENT_SECRET = "YOUR_SWITCHBOT_API_CLIENT_SECRET"
