"""
Configuration layer
"""

from .constants import (
    COLOR_BULB_CHECK_INTERVAL,
    DEEP_SLEEP_THRESHOLD,
    LIGHT_SLEEP_DURATION,
    LIGHT_SLEEP_THRESHOLD,
    POWER_ON_DURATION,
)

__all__ = [
    "COLOR_BULB_CHECK_INTERVAL",
    "DEEP_SLEEP_THRESHOLD",
    "LIGHT_SLEEP_DURATION",
    "LIGHT_SLEEP_THRESHOLD",
    "POWER_ON_DURATION",
]
